// Appointment action types
export const BOOK_APPOINTMENT_REQUEST = 'BOOK_APPOINTMENT_REQUEST';
export const BOOK_APPOINTMENT_SUCCESS = 'BOOK_APPOINTMENT_SUCCESS';
export const BOOK_APPOINTMENT_FAILURE = 'BOOK_APPOINTMENT_FAILURE';

export const FETCH_BOOKED_SLOTS_REQUEST = 'FETCH_BOOKED_SLOTS_REQUEST';
export const FETCH_BOOKED_SLOTS_SUCCESS = 'FETCH_BOOKED_SLOTS_SUCCESS';
export const FETCH_BOOKED_SLOTS_FAILURE = 'FETCH_BOOKED_SLOTS_FAILURE';

// Action types for fetching appointments and notifications
export const FETCH_APPOINTMENTS_REQUEST = 'FETCH_APPOINTMENTS_REQUEST';
export const FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS';
export const FETCH_APPOINTMENTS_FAILURE = 'FETCH_APPOINTMENTS_FAILURE';

export const CANCEL_APPOINTMENT_REQUEST = 'CANCEL_APPOINTMENT_REQUEST';
export const CANCEL_APPOINTMENT_SUCCESS = 'CANCEL_APPOINTMENT_SUCCESS';
export const CANCEL_APPOINTMENT_FAILURE = 'CANCEL_APPOINTMENT_FAILURE';

// Action types for fetching user appointments
export const FETCH_USER_APPOINTMENTS_REQUEST = 'FETCH_USER_APPOINTMENTS_REQUEST';
export const FETCH_USER_APPOINTMENTS_SUCCESS = 'FETCH_USER_APPOINTMENTS_SUCCESS';
export const FETCH_USER_APPOINTMENTS_FAILURE = 'FETCH_USER_APPOINTMENTS_FAILURE';

// New action types for updating appointments
export const UPDATE_APPOINTMENT_REQUEST = 'UPDATE_APPOINTMENT_REQUEST';
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS';
export const UPDATE_APPOINTMENT_FAILURE = 'UPDATE_APPOINTMENT_FAILURE';
