export const FETCH_DOCTOR_PROFILE_REQUEST = 'FETCH_DOCTOR_PROFILE_REQUEST';
export const FETCH_DOCTOR_PROFILE_SUCCESS = 'FETCH_DOCTOR_PROFILE_SUCCESS';
export const FETCH_DOCTOR_PROFILE_FAILURE = 'FETCH_DOCTOR_PROFILE_FAILURE';

export const UPDATE_PROFILE_PICTURE_REQUEST = 'UPDATE_PROFILE_PICTURE_REQUEST';
export const UPDATE_PROFILE_PICTURE_SUCCESS = 'UPDATE_PROFILE_PICTURE_SUCCESS';
export const UPDATE_PROFILE_PICTURE_FAILURE = 'UPDATE_PROFILE_PICTURE_FAILURE';
